name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull ianailex/demo-app:latest
      
    - name: Delete Old docker container
      run: sudo docker rm -f demo-app-container || true
      
    - name: Run Docker Container
      run: sudo docker start demo-app
